# Головний файл-інструкція для Fly.io
app = "TradeNews"
primary_region = "ams" # Можете залишити ams (Амстердам) або обрати інший регіон

[build]
  # Вказуємо, що для збірки будемо використовувати Dockerfile
  builder = "dockerfile"

# ЦЕ НАЙВАЖЛИВІША ЧАСТИНА
[processes]
  # Називаємо наш процес "app" і кажемо, що для його запуску потрібно виконати команду "python bot.py"
  # Fly.io не буде чекати на відкритий порт, а просто запустить команду.
  app = "python bot.py"
